# Dependencies
markdown:         redcarpet
highlighter:      pygments
highlighter:      true

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Matheus Ikeda
tagline:          'Iniciação Científica'
description:      'Base theme for Jekyll themes by @mdo.'
url:              http://getpoole.com

author:
  name:           'Matheus Ikeda'
  url:            https://facebook.com/matheus.yamakawa

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/poole
